PostHog/posthog-python

- README.md
> Fix typo with "identify" code example

- posthog/client.py
Was looking at the feature flags and came across a pretty bad pattern where we use an error for path handling in logic we have full control over.
> Better handling on feature_enabled

- example.py
- posthog/__init__.py
- posthog/client.py
Part of https://github.com/PostHog/posthog/issues/7010
On the API side we only need to pass forward the "groups" argument.
> Groups: Feature flags support

- CHANGELOG.md
- example.py
- posthog/__init__.py
- posthog/client.py
- posthog/request.py
- posthog/test/test_feature_flags.py
- posthog/version.py
Making the library more friendly to use, adheres to follow up spec: https://github.com/PostHog/posthog/issues/10459#issuecomment-1203042885
> fix(feature-flags): Add more options to make using library easier

- CHANGELOG.md
- posthog/__init__.py
- posthog/client.py
- posthog/test/test_feature_flags.py
- posthog/version.py
Also fixes https://github.com/PostHog/posthog-python/issues/71
Reason -> Additional spec: https://github.com/PostHog/posthog/issues/10459#issuecomment-1211935866
> fix: Remove defaults for feature flag calls

- posthog/client.py
- posthog/test/test_client.py
- setup.py
Addresses https://github.com/PostHog/posthog-python/issues/78
I don't see any issue with newer versions
> chore: Remove upper bound

- posthog/test/test_client.py
test was left as a print with no assertion!
> chore: fix active flag test

- CHANGELOG.md
- posthog/client.py
- posthog/feature_flags.py
- posthog/test/test_feature_flags.py
- posthog/version.py
Part of https://github.com/PostHog/meta/pull/90
Enables locally evaluating all cohorts.
> feat(flags): Enable local evaluation for all cohorts

- posthog/client.py
This was introduced in the latest version of the library.
> Remove print() call

- CHANGELOG.md
- posthog/version.py
> Release version 2.5.0

- CHANGELOG.md
- posthog/__init__.py
- posthog/version.py
Noticed some borking while trying to update: https://github.com/PostHog/posthog/pull/20033#pullrequestreview-1851573570
> chore(flags): Update type hints for newer mypy versions

- CHANGELOG.md
- posthog/client.py
- posthog/request.py
- posthog/test/test_client.py
- posthog/test/test_request.py
- posthog/version.py
Tested locally for different hosts, see things work fine
> fix(routing): Update hosts to point to right ingestion host

- CHANGELOG.md
- posthog/client.py
- posthog/version.py
> chore: Use ingestion hosts for event capture

- CHANGELOG.md
- posthog/version.py
https://github.com/PostHog/posthog-python/pull/117#issuecomment-1946577341
> Bump to 3.4.2

- CHANGELOG.md
- posthog/__init__.py
- posthog/client.py
- posthog/test/test_client.py
- posthog/version.py
> fix(flags): Add a shorter configurable timeout for flag requests

- CHANGELOG.md
- posthog/version.py
> bump version to 3.5.2

- CHANGELOG.md
- posthog/version.py
- setup_analytics.py
> fix(setup): Make sure all packages are bundled

- CHANGELOG.md
- posthog/exception_capture.py
- posthog/version.py
missed one place for the update 🤦‍♂️
> fix: Update Django integration for manual capture

- CHANGELOG.md
- posthog/exception_utils.py
- posthog/test/test_exception_capture.py
- posthog/version.py
Similar to https://github.com/PostHog/posthog-js/pull/1495
We want to know the `lang` of each frame so that we can switch on it in Rust
> chore: add lang to frames

- posthog/version.py
my changes got lost in a merge conflict I think
> fix(flags): bump the version

- CHANGELOG.md
- posthog/version.py
- setup.py
- setup_analytics.py
need to add new ai stuff to setup
> fix: update to export module

- llm_observability_examples.py
- posthog/__init__.py
- posthog/ai/langchain/callbacks.py
- posthog/ai/openai/openai.py
- posthog/ai/openai/openai_async.py
- posthog/ai/utils.py
- posthog/client.py
- posthog/test/ai/langchain/test_callbacks.py
- posthog/test/ai/openai/test_openai.py
add privacy mode for AI observability
> feat: privacy_mode

- CHANGELOG.md
- llm_observability_examples.py
- posthog/ai/openai/__init__.py
- posthog/ai/openai/openai_providers.py
- posthog/version.py
Add Azure Support for Posthog wrapped Open Ai Python SDK
> feat: azure export w/ async

- posthog/version.py
> bump version

- CHANGELOG.md
- posthog/__init__.py
- posthog/version.py
Follow on to https://github.com/PostHog/posthog-python/pull/215. Just forgot to add the extra config when calling as a singleton
> fix: add field to proxy client setup

- bin/build
- bin/fmt
- bin/helpers/_utils.sh
- bin/setup
- bin/test
- posthog/test/test_feature_flags.py
- posthog/types.py
See https://github.com/PostHog/posthog/issues/30569 for why I'm making this change to `condition_index`.
See PostHog/meta#309 for the rationale behind these scripts.
> chore: Make `condition_index` optional. Also added some scripts for local dev.

- CHANGELOG.md
- posthog/version.py
> fix: bump for release

- CHANGELOG.md
- posthog/client.py
- posthog/test/test_client.py
- posthog/version.py
Closes the Python requirement for https://github.com/PostHog/posthog/issues/33331
> chore(flags): roll everyone onto `/flags`
