- posthog/__init__.py
Just had a first look into the package and stumbled upon this lil typo.
> Fix typo in identify() docstring

- posthog/__init__.py
Currently we have two defaults set in the chain. At the top it defaults the flag to None. Later we default to False even though we always pass None in making that default moot.
> Default to False if the feature flag key does not exist. None is confusing

- .gitignore
- posthog/client.py
- To complement https://github.com/PostHog/posthog/issues/2150#issuecomment-732174233 and https://github.com/PostHog/posthog/pull/2473
- Moves the "no personal api key found" warning and `return` statement one level higher, thus never starting the poller if no api key found.
> Do not start Feature Flag polling if no API Key

- posthog/test/utils.py
- posthog/utils.py
This should handle UUIDs by converting them to strings instead of crashing the analytics request. Proper fix to PostHog/posthog#2199.
> Allow passing in UUID as property

- posthog/client.py
- posthog/request.py
- Add a `project_api_key` config param to be used instead of `api_key` help minimize confusion on the type of key to use. This is backwards compatible with `api_key` and the docs will be updated accordingly
- Consolidate repeated code
- Handle a case when response is equal to `None`, leading to errors that aren't helpful such as:
```
error uploading: 'NoneType' object has no attribute 'status_code'
```
> Add project_api_key, improve errors

- posthog/client.py
Quick patch for [this sentry error](https://sentry.io/organizations/posthog/issues/2178357897/?project=1899813) so the request will just be sent to the decide endpoint.
Need further investigation as to why that field isn't populated
> Add condition for rollout-percentage

- .gitignore
- posthog/client.py
- posthog/test/client.py
Makes `UUID` an accepted ID type. No changed in processing code needed, as `stringify_id` already `str()`-casts IDs. Resolves #25.
> Add UUID to ID_TYPES

- posthog/client.py
- posthog/consumer.py
Alias event generated by the current code looks like this:
```{
'properties': {'distinct_id': 'anon-6666666666666', 'alias': 'public-2', '$lib': 'posthog-python', '$lib_version': '1.2.1'}, 'timestamp': '2021-05-07T05:41:05.037966+00:00', 'context': {}, 'event': '$create_alias', 'messageId': 'daab4896-44d5-4c13-8ea5-9d9490be6145', 'distinct_id': None}
```
And since `distinct_id` is none it does not work as expected.
This patch tries to fix that problem by adding `distinct_id` to the event.
> fix: Add distinct id to $create_alias event

- posthog/test/test_client.py
Test wasn't passing because set_once branch wasn't uptodate with master. Now ID_TYPES includes UUID. Refer to #26 and #25
> Revert UUID test change

- posthog/client.py
- posthog/test/test_client.py
> Fix feature flag issue with no % rollout

- example.py
- posthog/client.py
- posthog/poller.py
Fixes #16 
Tested using `example.py`: it blocked when a valid personal API key was set, but doesn't anymore.
> Resolve polling issues with feature flags

- example.py
- posthog/__init__.py
- posthog/client.py
- posthog/consumer.py
- posthog/test/test_client.py
Fixes #31
This doesn't remove `api_key` yet, but supports both `project_api_key` and `api_key`.
> Add support for project_api_key. 

- setup.py
Bump backoff dependency as per analytics-python PR https://github.com/segmentio/analytics-python/pull/173.
Have fixed to 1.10.0 as per other PR - however may be better to keep as `>=1.6.0` or so for backwards compatibility.
> Bump backoff dependency to 1.10.0

- setup.py
Have modified the backoff dependency so that it handles any future (minor & patch) releases - this helps with merging the library into conda/conda-forge - see https://github.com/conda-forge/staged-recipes/pull/15012
> Remove pinning of backoff dependency

- .gitignore
- posthog/client.py
- posthog/test/test_client.py
Ignores flags that aren't active, and accompanies PostHog/posthog#4764 to fix the issue with the project being able to change.
> Fix integrity issues

- .github/workflows/release.yaml
- README.md
- posthog/version.py
This way any PostHog member will be able to release a new version of `posthog-python`, instead of having to become a PyPI collaborator (much more cumbersome).
CC @yakkomajuri
> Add release workflow

- posthog/sentry/posthog_integration.py
- sentry_django_example/sentry_django_example/settings.py
From user feedback, we now use the Sentry DSN to obtain the project ID when building the `$sentry_url` property. Unfortunately the DSN doesn't contain the organization_id so the user will still need to type that.
> Use Sentry DSN to obtain project ID

- posthog/__init__.py
- posthog/client.py
- posthog/test/test_client.py
- posthog/test/test_consumer.py
The library used to have a `message_id` value you can attach to your events, but this value was effectively ignored.
This PR replaces that with a `uuid` value that is actually respected by the plugin server, but only if it's a real `uuid`. 
This came from a customer request in Slack.
> Support custom UUID values

- posthog/__init__.py
The call doesn't work if you include `id:` into it, but maybe I am misunderstanding?
> docs:Remove id: from example

- README.md
- posthog/client.py
- posthog/test/test_client.py
Most feature flags require a call to decide anyway, so we might as well allow feature flags without first grabbing all active feature flags.
> fix: Personal api key not required

- posthog/client.py
- posthog/request.py
- posthog/test/test_client.py
Using the v2 decide endpoint. Should be merged after https://github.com/PostHog/posthog-python/pull/57 as that pull request fixes how feature flags are captured on Posthog.
> Feature: Enable multi variate feature flags for Python library

- CHANGELOG.md
- posthog/feature_flags.py
- posthog/test/test_feature_flags.py
- posthog/version.py
- add handling date evaluation to prop matching in local evaluation
TODO:
- make changes to all libraries
> feat: add date comparison to local evaluation

- CHANGELOG.md
- posthog/feature_flags.py
- posthog/test/test_feature_flags.py
- posthog/utils.py
- posthog/version.py
Have gone for a naive datetime approach here, so we disregard timezone information. Not sure if we want to handle this / if there's valid usecases for this yet.
> fix: datetime comparison issues

- CHANGELOG.md
- README.md
- example.py
- posthog/feature_flags.py
- posthog/test/test_feature_flags.py
- posthog/version.py
Following what main branch does here: https://github.com/PostHog/posthog/pull/12652 for local evaluation
> feat(flags): Add support for variant overrides

- example.py
- posthog/__init__.py
- posthog/client.py
- posthog/request.py
- posthog/test/test_feature_flags.py
- implements https://github.com/PostHog/posthog/issues/13627 for posthog-python
- get_feature_flag_payload
- get_all_flags_and_payloads
- change api to v=3
> feat(feature-flags): JSON payload function

- posthog/client.py
- posthog/test/test_client.py
- posthog/test/test_feature_flags.py
Context: https://posthog.slack.com/archives/C04LVFQ481Y/p1674834256925379
Incorrect api key was causing error to be thrown. Change error handling to be a log
> fix: change api error to log

- posthog/client.py
- posthog/test/test_client.py
Send feature flags is sending all flags now after decide v3 change. Restore original functionality
> fix: add function for active variants

- posthog/__init__.py
- posthog/client.py
- posthog/test/test_client.py
- posthog/test/test_module.py
Using global client is setting up for failure if there are overlapping posthogs in a dependency and the project using the depency
Changes:
- wrap the function headers in __init__.py to be an object that can be instantiated
Note: This is a major version change as it breaks the current pattern
> chore: change package to be an instantiable client

- CHANGELOG.md
- posthog/__init__.py
- posthog/client.py
- posthog/test/test_client.py
- posthog/test/test_feature_flags.py
- posthog/version.py
https://github.com/PostHog/posthog/issues/14351
The `$geoip` property on server libraries tends to default to incorrect locations (mainly based from where the server is located and not the user) and causes issues such as incorrect event/user data for analytics and problems with feature flag rollouts based on location.
This fix prevents the `advanced geoip plugin` and the `decide` call in https://github.com/PostHog/posthog/blob/master/posthog/api/decide.py#L144 from overriding user properties with incorrect server library geoip properties by default.
Users who are manually passing in geoip values will have to set `geoip_disable` to `False` to ensure their values are not discarded
related PR: https://github.com/PostHog/posthog/pull/15039
> Disable geoip for capture and decide calls by default

- CHANGELOG.md
- posthog/__init__.py
- posthog/client.py
- posthog/test/test_client.py
- posthog/version.py
Disable used to return none for feature flags as well, but this behaviour broke with the client refactor.
Noticed while trying to update client to latest version
> fix: disable behaviour for feature flags

- .github/workflows/ci.yml
- CHANGELOG.md
- posthog/consumer.py
- posthog/test/test_consumer.py
- posthog/version.py
- setup.py
Our limits were too conservative, leading to legitimate events being dropped. Let's raise:
- event size 32KB -> 900KiB (hard limit 1MiB)
- batch size 500KB -> 5MiB (hard limit 20MiB)
> feat: increase message and batch sizes

- CHANGELOG.md
- posthog/feature_flags.py
- posthog/test/test_feature_flags.py
- posthog/version.py
Copy of https://github.com/PostHog/posthog/pull/18359/  https://github.com/PostHog/posthog/pull/18349 and https://github.com/PostHog/posthog/pull/18321/ but for SDKs. All other SDKs to follow
> feat(flags): Add relative date operators, fix numeric ops

- CHANGELOG.md
- example.py
- posthog/client.py
- posthog/test/test_client.py
- posthog/version.py
Part of updating all SDKs to allow targeting by distinct id / group id;
and send all flags which can be computed locally with events. - https://github.com/PostHog/posthog/issues/14270
> feat(flags): Add local props and flags to all calls

- CHANGELOG.md
- posthog/client.py
- posthog/test/test_client.py
- posthog/version.py
Noticed when testing that this can override existing values, which we don't want because we only evaluate locally and can miss some flags / incorrectly assign a value.
> fix(flags): Don't override existing props when adding flags

- CHANGELOG.md
- posthog/__init__.py
- posthog/test/test_module.py
- posthog/version.py
Emulating the behavior of the Client by returning the result of the `Client.__enqueue()` method when called through `_proxy()` at the module level.
This can be particularly useful to debug eventual issues when one is not using the client but the functions available at the module.
> Module functions to also return the same as its Client equivalent

- posthog/client.py
- posthog/consumer.py
[`**kwargs` is turned into `body` and just JSON serialized](https://github.com/PostHog/posthog-python/blob/ba7a77c21b5f5a15241bf3e7cf518c41601fd318/posthog/request.py#L39-L44). That's how `batch` even gets into the body, which is a sibling to `historical_migration` as we'd expect.
The idea is we'd just pass `historical_migration=True` in the migration script here: https://github.com/PostHog/posthog-migration-tools/blob/ae2429c58bff15801eeace078b259ba2dfc9b9fd/migrate.py#L172
> Add historical_migration option to toplevel Client

- posthog/feature_flags.py
- posthog/test/test_feature_flags.py
Porting over the fix from `posthog-node` to `posthog-python` : https://github.com/PostHog/posthog-js-lite/pull/249
The current behavior of stringifying `None` values to compare with operators can lead to invalid results in local evaluation. 
This causes local evaluation to return `true`, while the `/decide` API does the right thing and returns false for `undefined` values in these properties.  
Customer reported that local evaluation always evaluates a condition to true, when it should evaluate to false. 
The conditions in question are : 
``` json
[
{
"key": "latestBuildVersion",
"type": "person",
"value": ".+",
"operator": "regex"
},
{
"key": "latestBuildVersionMajor",
"type": "person",
"value": "23",
"operator": "gt"
},
{
"key": "latestBuildVersionMinor",
"type": "person",
"value": …
```
> fix(feature flags): Guard for None values when comparing person Properties

- CHANGELOG.md
- posthog/version.py
- setup.py
I want to replace this with `find_packages()` so it doesn't happen again, but ugh backwards compatibility
> fix(setup): Make sure all packages are bundled

- CHANGELOG.md
- posthog/__init__.py
- posthog/client.py
- posthog/test/test_client.py
- posthog/version.py
> fix(errors): Make sure project root exists to judge in app frames

- CHANGELOG.md
- posthog/__init__.py
- posthog/client.py
- posthog/test/test_client.py
- posthog/version.py
Customers of error tracking want to know what repository a particular exception came from by filtering in the UI. Rather than adding some specific property (e.g. `exception_source_identifier`) that would then need to be added to the JS SDK and any other language we support in future, I thought it would be easier to reuse the super properties concept found in our other SDKs 
I'm not tied to this approach but "PRs > Slack" and all that... Open to feedback here.
- Went with a very basic implementation that allows you to set `super_properties` when initialising the client
- Could have gone with the `register` method seen elsewhere but didn't want to mislead customers into thinking that properties were somehow stored elsewhere (like they are in local storage). Better to make sure that they're …
> feat: add super properties

- CHANGELOG.md
- posthog/exception_utils.py
- posthog/test/test_client.py
- posthog/version.py
`type` required to parse stack traces in cymbal
> chore: add type to stack

- CHANGELOG.md
- posthog/client.py
- posthog/test/test_client.py
- posthog/version.py
-  https://github.com/PostHog/posthog-python/issues/137
- This PR adds the capability of passing distinct_id to the group_identify() function in the PostHog Client
- This allows the users to tag a group identify event to a person ID
**Before**
**After**
Sample code :
```python
group_type = "business"
group_key = 2668  # business_id
distinct_id=2675  # user_id
ph_client = posthog.Client(api_key=POSTHOG_API_KEY)
ph_client.group_identify(group_type, group_key, properties, distinct_id=distinct_id)
```
> [FEATURE]Add distinct_id to group_identify

- CHANGELOG.md
- posthog/version.py
- setup.py
The distributed package only has the `posthog.ai` module without the `posthog.ai.openai` and `posthog.ai.langchain` modules since they're not exported from `posthog/ai/__init__.py`.
> fix(llm-observability): include the ai packages

- CHANGELOG.md
- posthog/version.py
- setup_analytics.py
This is the same as #162 but includes the AI packages for the `posthoganalytics` package. I completely forgot about it.
> feat(llm-observability): add new packages for posthoganalytics

- posthog/ai/langchain/callbacks.py
- posthog/test/ai/langchain/test_callbacks.py
OpenAI wrappers send data as:
```json
{
"role": "assistant",
"content": "",
"tool_calls": [
{
"type": "function",
"id": "123",
"function": {
"name": "test",
"args": "{\"a\": 1}",
},
}
]
}
```
But the Langchain integration adds the tool calls into the `additional_kwargs` field:
```json
{
"role": "assistant",
"content": "",
"additional_kwargs": {
"tool_calls": [
{
"type": "function",
"id": "123",
"function": {
"name": "test",
"args": "{\"a\": 1}"
}
}
]
}
}
```
Flatten `additional_kwargs` to mirror the OpenAI wrapper to remove the discrepancies.
> fix(llm-observability): flatten langchain's additional_kwargs

- .github/workflows/ci.yml
- posthog/ai/langchain/callbacks.py
- posthog/test/ai/langchain/__init__.py
- posthog/test/ai/langchain/test_callbacks.py
- setup.py
This adds `$ai_trace` tracking to the LangChain `CallbackHandler`, which captures top-level chain/graph inputs & outputs once it's done (or errored).
Related: improved debugging of chain/graph events, helping develop the callback handler.
Includes test coverage for both LangChain and LangGraph+LangChain.
> feat(llm-observability): LangChain tracing, with LangGraph tests

- posthog/ai/langchain/callbacks.py
- posthog/test/ai/langchain/test_callbacks.py
- posthog/version.py
Traces implementation doesn't catch parallel traces if a single instance of LangChain callbacks is used.
Store multiple parallel traces in the trace storage. Also, I've added capturing of trace latency.
> fix(llm-observability): parallel traces

- CHANGELOG.md
- posthog/test/test_utils.py
- posthog/utils.py
- setup.py
Pydantic models are skipped by default. This behavior is annoying and unclear for customers.
Serialize Pydantic objects to dicts:
- For v1, use the `dict` method.
- For v2, use the `model_dump` method.
If something goes wrong during serialization, omit the key.
> fix: serialize pydantic models

- CHANGELOG.md
- posthog/ai/langchain/callbacks.py
- posthog/test/ai/langchain/test_callbacks.py
- posthog/version.py
We want to capture the input and output of intermediary chains during agent workflows.
- Add the spans support for the LangChain callback handler.
- Replace the RunMetadata dict with dataclasses.
- Fix tests.
New fields:
- `$ai_parent_id` to capture a parent ID and build a tree.
- `$ai_generation_id` to capture a generation ID and unify API.
- `$ai_span_id` to capture an ID for a span.
> feat(llm-observability): LangChain spans

- CHANGELOG.md
- posthog/ai/langchain/callbacks.py
- posthog/version.py
I believe we should have:
self._set_parent_of_run(run_id, parent_run_id)
on each of the callbackStart methods
> fix: langchain tool parent add

- posthog/client.py
- posthog/feature_flags.py
- posthog/test/test_feature_flags.py
`flag_variants` doesn't depend on condition so it doesn't make sense to declare it in the loop.
> Move accessing variants outside of loop

- example.py
This is a little quality of life improvement. When using the example script, it creates an event for the feature flag `person-on-events-enabled`. This change adds an optional argument that lets you change the feature-flag key for the event like so:
```bash
python3 example.py --flag person-on-events-enabled-v1
```
If the flag is omitted, the script behaves the same as it always did.
> Allow specifying the flag in the example script

- posthog/__init__.py
- posthog/client.py
- posthog/test/test_client.py
- simulator.py
It's not used anywhere, a vestigial remnant of a time long ago.
This PR supercedes https://github.com/PostHog/posthog-python/pull/54.
> Deprecate the context argument

- CHANGELOG.md
- llm_observability_examples.py
- posthog/ai/openai/openai.py
- posthog/ai/openai/openai_async.py
- posthog/version.py
Add support for the  `client.beta.chat.completions.parse` method
Example:
`
class CalendarEvent(BaseModel):
name: str
date: str
participants: list[str]
def beta_openai_call(distinct_id, trace_id, properties, groups):
response = openai_client.beta.chat.completions.parse(
model="gpt-4o-mini",
messages=[
{"role": "system", "content": "Extract the event information."},
{"role": "user", "content": "Alice and Bob are going to a science fair on Friday."},
],
response_format=CalendarEvent,
posthog_distinct_id=distinct_id,
posthog_trace_id=trace_id,
posthog_properties=properties,
posthog_groups=groups,
)
print(response)
return response
`
> feat: add beta parse method support

- posthog/client.py
- posthog/test/test_feature_flags.py
The `client.get_feature_flag` method will by default call `client.capture` with the event named `$feature_flag_called`. 
Some time ago (in e60d52c199ef75ac4e7b0aa962a2c892c94c9efc), the `capture` method was changed to enrich the event with all locally cached feature flags even if `send_feature_flags` is `False`.
What this leads to is `client.get_feature_flag` -> `client.capture` -> `client.get_all_flags`. But the call to `client.get_all_flags` isn't passed the original `person_properties` that were passed to `client.get_feature_flag`. This leads to inconsistency in the enriched data. This can also cause confusion because it's unclear which feature flag is the one being called because the event adds "all" the locally cached feature flags.
This PR takes the simplest path by not enriching …
> Stop capturing all feature flags on `$feature_flag_called` event.

- posthog/test/test_client.py
- posthog/test/test_feature_flags.py
It's no longer used anywhere. This is just cleanup code.
> Remove the usage of `is_simple_flag`

- CHANGELOG.md
- posthog/__init__.py
- posthog/version.py
This is incorrect, we should've added these slightly lower in the method definition to avoid mypy from breaking
Closes #187
> fix: Move code under mypy type

- posthog/feature_flags.py
- posthog/test/test_feature_flags.py
- posthog/utils.py
Calling `lower()` on two strings in order to compare them is incorrect in some cases (297 as of Unicode 13.0.0). For example, the lower case of `Straße` has two correct values: `straße` and `strasse`.
This PR adds a failing unit test that demonstrates the problem. Then it replaces string comparisons using `lower()` with `casefold()` to ensure the test passes.
This aligns with the official Python [docs on casefold](https://docs.python.org/3/library/stdtypes.html#str.casefold) which notes (emphasis mine): 
> Return a casefolded copy of the string. __Casefolded strings may be used for caseless matching.__
Contrast this with what the Unicode standard [Section 3.13](https://www.unicode.org/versions/Unicode13.0.0/ch03.pdf) has to say about changing the case vs case folding:
> Case folding is …
> Use casefold to compare strings case insensitively

- CHANGELOG.md
- posthog/ai/langchain/callbacks.py
- posthog/version.py
add support for bedrock usage in completion while using langcahin - edge case
> fix: support usage as part of generation

- CHANGELOG.md
- posthog/client.py
- posthog/test/test_feature_flags.py
- posthog/version.py
Remove `lower()` when evaluating feature flags + feature flag payloads – feature flags are case-sensitive.  Closes https://github.com/PostHog/posthog-python/issues/178
> fix(flags): remove `lower()` when evaluating feature flag payloads – these payloads are case-sensitive!

- CHANGELOG.md
- posthog/client.py
- posthog/request.py
- posthog/test/test_client.py
- posthog/test/test_feature_flags.py
- posthog/test/test_request.py
- posthog/version.py
with [this PR](https://github.com/PostHog/posthog/pull/28564), we now start to respond different with the `/decide` and `/local_evaluation` APIs if users have gone over their quota limit.  This change is an example for how our SDKs can deal with that.  I'll make the same type of changes to all of the SDKs, but wanted to start with this one as an example.
> feat(feature-flags): support quota limiting for feature flags

- CHANGELOG.md
- README.md
- posthog/client.py
- posthog/test/test_client.py
- posthog/version.py
- setup.py
this isn't very useful in product analytics but would be super useful in error tracking
> feat: add some platform info to events

- CHANGELOG.md
- posthog/ai/langchain/callbacks.py
- posthog/test/ai/langchain/test_callbacks.py
- posthog/version.py
Tools are part of the LLM input prompt, and we haven't been capturing them at all in LLM observability!
This PR adds capturing of tools as `$ai_tools` to the Langchain callback handler. Does not touch SDK wrappers.
> feat(llm-observability): `$ai_tools` capture in Langchain

- CHANGELOG.md
- posthog/ai/openai/openai.py
- posthog/ai/openai/openai_async.py
- posthog/version.py
Add a check for delta before getting contents otherwise azure will not work with streaming
> fix: azure open ai delta check

- CHANGELOG.md
- setup_analytics.py
@pauldambra I think you forgot to add `distro` for the analytics package
> fix: distro requirement for analytics package

- CHANGELOG.md
- posthog/test/test_utils.py
- posthog/utils.py
- posthog/version.py
Adds support for serializing Python dataclasses in event data.
> feat: Support serializing dataclasses

- CHANGELOG.md
- posthog/__init__.py
- posthog/client.py
- posthog/feature_flags.py
- posthog/request.py
- posthog/test/ai/openai/test_openai.py
- posthog/test/test_client.py
- posthog/test/test_feature_flag.py
- posthog/test/test_feature_flags.py
- posthog/test/test_request.py
- posthog/test/test_types.py
- posthog/types.py
- posthog/version.py
Add support for `/decide?v=4` (see https://github.com/PostHog/posthog/pull/29751). Similar to how it's done in https://github.com/PostHog/posthog-js-lite/pull/427.
When capturing the `$feature_flag_called` event, additional information are now captured:
The end result is `$feature_flag_called` events will have additional properties:
| Property Name                |  Descirption
| ------------------------ | -------------
| `$feature_flag_version` | The version of the feature flag. This is visible in the diffs of the feature flag activity log.
| `$feature_flag_reason` | The reason the feature flag matched or didn't match.
| `$feature_flag_id`          | The database id of the feature flag (Just in case a flag was deleted and then recreated with the same key, we can determine the difference. …
> feat(flags): Add more details such as version, id, and reason to `$feature_flag_called` events

- CHANGELOG.md
- posthog/request.py
in e.g. lambda environments the connection can time out between invocations, this comes through to the client as a "RemoteDisconnected" error, which it turns out urllib classifies as a "read" error not a connection error (as it's possible to get this error after data has been sent)
follow up to https://github.com/PostHog/posthog-python/pull/190
> update automatic retries to include read errors

- CHANGELOG.md
- posthog/__init__.py
- posthog/client.py
- posthog/test/test_client.py
- posthog/version.py
Adds a `log_captured_exceptions` config option so that all `$exception` events can also be logged
This is useful internally to capture exceptions if our own product is unavailable.
We have a version of this already in https://github.com/PostHog/posthog/blob/c2c65827b31b13c8e2e84d4ddc33df34b5924487/posthog/exceptions.py#L58-L66 but that only applies to DFR views.
By doing this at the SDK level we can log _any_ exception that is being captured. One difference is that the logger in the SDK is not structured but I think that's ok
> feat: log captured exceptions

- posthog/test/ai/langchain/test_callbacks.py
The failure of `posthog/test/ai/langchain/test_callbacks.py::test_graph_state` on #218 is caused by the very recent [LangGraph 0.3.29](https://github.com/langchain-ai/langgraph/releases/tag/0.3.29) release, which has changed the callbacks fired. Seemingly it's the https://github.com/langchain-ai/langgraph/pull/4247 PR.
In concrete terms, LangGraph 0.3.29+ does not register `ChannelWrite<...>` spans, and doesn't capture `__start__` unless it has a conditional edge.
This PR updates `test_graph_state` to reflect the current behavior of LangGraph.
> test(llm-observability): Account for LangGraph 0.3.29 changes

- .github/workflows/release.yaml
updating our release job for `posthog-python` since GH actions have officially discontinued 20.04.
> ubuntu 20.04 is EOL

- CHANGELOG.md
- posthog/client.py
- posthog/test/test_client.py
- posthog/test/test_feature_flags.py
- posthog/version.py
rolled the percentage to 100%.  Let's get some real data.
> chore(flags): latest version of `posthog-python` now uses `/flags` by default, except for a few exceptions

- bin/fmt
- bin/helpers/_utils.sh
- bin/setup
- bin/test
- posthog/test/ai/anthropic/test_anthropic.py
- posthog/test/ai/langchain/test_callbacks.py
- posthog/test/ai/openai/test_openai.py
- posthog/test/test_feature_flag.py
- posthog/test/test_feature_flags.py
And make sure we activate properly.
This doesn't affect any library code, just tooling around working on the project.
> chore: Add parameters to `bin/test`

- CHANGELOG.md
- posthog/consumer.py
- posthog/version.py
- setup.py
- setup_analytics.py
This library has been long-deprecated (2021). We can use `time.monotonic` instead which has been available since Python 3.3
Closes #230
> feat: Remove deprecated `monotonic` lib

- CHANGELOG.md
- posthog/ai/openai/openai.py
- posthog/ai/openai/openai_async.py
- posthog/ai/openai/openai_providers.py
- posthog/version.py
- setup.cfg
Support both new and old openai sdks (since resource change) by changing to a composition approach over inheritance. This means we do not need to import the resources and should be more defensive to dependency changes
fixes: https://github.com/PostHog/posthog-python/issues/234
> feat: composition over inheritance

- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- mypy-baseline.txt
- posthog/test/test_size_limited_dict.py
- posthog/test/test_utils.py
- posthog/utils.py
- posthog/version.py
copyable setup block in readme so i don't have to figure it out again in future
we also had some python 3 unsafe code that we're luckily only calling in a safe way right now that mypy was incidentally warning us about. should do a patch release with this change
> fix: opinionated setup and clean fn fix

- CHANGELOG.md
- Makefile
- posthog/version.py
- pyproject.toml
- setup_analytics.py
- uv.lock
the posthog_analytics release was broken in the recent reorganisation of files
* update setup_analytics.py to change values in pyproject.toml instead of having the info duplicated in the 2 setup files
* update the makefile to tidy up a little more
* update the makefile so it can run if there's a pycache directory present
> fix: makefile for posthog_analytics release

- .github/workflows/release.yaml
- CHANGELOG.md
- Makefile
- posthog/version.py
- pyproject.toml
ok, next error
```
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
rm -rf posthog
python setup_analytics.py sdist bdist_wheel
Traceback (most recent call last):
File "/home/runner/work/posthog-python/posthog-python/setup_analytics.py", line 3, in <module>
import tomli
ModuleNotFoundError: No module named 'tomli'
```
two things
an error we've not seen or ignored because we're using `sed` with a mac os flag that doesn't work on linux in CI
and then installing tomli in the wrong dependency group
> chore: more fiddling to get release working

- CHANGELOG.md
now that the release process is fixed we can update the changelog so that it matches pypi
https://pypi.org/project/posthog/#history
> fix changelog to match pypi

- BEFORE_SEND.md
- CHANGELOG.md
- posthog/client.py
- posthog/test/test_before_send.py
- posthog/types.py
- posthog/version.py
we've got this in posthog-js and posthog-ruby
let's add it here
ultimate power to edit/drop/fix events as you see fit
> feat: add before_send callback

- CHANGELOG.md
- Makefile
- posthog/version.py
Getting an error when trying to use the new context scopes feature because we call `import posthog`. This fails because the Makefile doesn't replace the call with `import posthoganalytics`
> fix: makefile import

- CHANGELOG.md
- Makefile
- posthog/scopes.py
- posthog/sentry/posthog_integration.py
- posthog/test/test_client.py
- posthog/version.py
Follow on from https://github.com/PostHog/posthog-python/pull/254
That PR had the intended effect of replacing `import posthog` with `import posthoganalytics`. I failed to realise that everywhere `posthog.{method_name}` was called also needed replacing. Going to try this simpler approach of never importing the entire package
> remove 'import posthog'

- CHANGELOG.md
- posthog/ai/openai/openai.py
- posthog/ai/openai/openai_async.py
- posthog/test/ai/openai/test_openai.py
- posthog/version.py
Parse has been added to openAI's responses api out of beta. Lets support it
> feat: add support for parse via responses

- CHANGELOG.md
- posthog/__init__.py
- posthog/scopes.py
- posthog/version.py
Figured while I was here we may as well let people use the tagging infrastructure without forcing them to use error tracking - it seems like a nice pattern for using posthog generally.
I do think we should default opt-in to error tracking tho - if we get complaints, we can expose a global config to disable it at the client level, but capturing exceptions in the most deeply nested context means getting the most tags on them, which is the ideal scenario.
> fix: change scoped export, add capturing param

- .github/workflows/call-flags-project-board.yml
This adds a workflow for the Feature Flags team's project board. See https://github.com/PostHog/.github/pull/1 for more context.
> chore(flags): Add flags project board workflow

- mypy-baseline.txt
- posthog/client.py
- posthog/exception_utils.py
- posthog/integrations/django.py
- posthog/test/integrations/test_middleware.py
The distinct_id bit is currently kind-of unused - I'm going to add additional machinery and handling for it in future PRs
> feat(err): add django middleware

- CHANGELOG.md
- Makefile
- posthog/__init__.py
- posthog/client.py
- posthog/integrations/django.py
- posthog/scopes.py
- posthog/test/integrations/test_middleware.py
- posthog/test/test_scopes.py
- posthog/version.py
- pyproject.toml
> feat: session and identity integrate with context now

- CHANGELOG.md
- posthog/exception_utils.py
- posthog/test/test_client.py
- posthog/version.py
This goes with the reversed-full-stack approach. It is naive to async considerations. Options below:
Original
Naive full stack:
Reversed full stack:
> feat(err): construct full trace if no traceback available

- README.md
There is no need to manually trigger the release pipeline anymore on usual cases
> docs: update release details on readme

- CHANGELOG.md
- posthog/args.py
- posthog/client.py
- posthog/version.py
> fix: default send_feature_flags false for capture_exception

- CHANGELOG.md
- posthog/__init__.py
- posthog/client.py
- posthog/test/test_client.py
- posthog/version.py
Parity with the Node SDK changes I made [here](https://github.com/PostHog/posthog-js-lite/pull/559/)
> feat(flags): decouple local evaluation from personal API keys; support decrypting remote config payloads without relying on the feature flags poller

- CHANGELOG.md
- posthog/integrations/django.py
- posthog/version.py
- uv.lock
Originally reported by @jamesbrewerdev in https://github.com/PostHog/posthog-python/issues/286
Django has its own exception handler for views and middleware that catches and processes exceptions. We need to hook into that and capture the exception manually. There might be some followup work needed here to process stack traces correctly but given this is pretty critical I'll follow up with that if necessary
Verified by manually editing the package (hence the old version number) that the view exception is correctly captured (including the context tags for URL etc)
> fix: capture django processed exceptions

- posthog/ai/langchain/callbacks.py
- posthog/test/ai/langchain/test_callbacks.py
Following up on [this PR](https://github.com/PostHog/posthog-python/pull/291), this generates a default PostHog client for LangChain if it's not passed during `CallbackHandler`'s instantiation.
> feat(llmo): Use default PH client for LangChain

- CHANGELOG.md
- posthog/args.py
- posthog/client.py
- posthog/test/test_client.py
- posthog/types.py
- posthog/version.py
The current `send_feature_flags` boolean parameter provides limited control over feature flag evaluation behavior. Users couldn't specify evaluation preferences or custom properties per capture event.
Modified `send_feature_flags` to accept either:
- `bool` (existing behavior, fully backward compatible)
- `SendFeatureFlagsOptions` object with granular control:
```python
{
"only_evaluate_locally": bool,     # Force local vs remote evaluation
"person_properties": dict,         # Custom properties for this event
"group_properties": dict           # Custom group properties
}
```
- **Declarative control**: Explicitly specify local vs remote evaluation per event
- **Custom properties**: Supply event-specific properties without affecting global state
- **Backward compatible**: Existing boolean …
> feat(flags):  make the sendFeatureFlags parameter more declarative and ergonomic

- CHANGELOG.md
- posthog/ai/utils.py
- posthog/test/ai/anthropic/test_anthropic.py
- posthog/version.py
The anthropic response handler when there are tool calls is broken for two reasons:
1. It tries to access a field that doesn't exist when the response is a tool call (`text`).
2. It doesn't properly capture tool calls to send as `$ai_tools` to PostHog.
This fixes both problems. Here's a sample response with a tool call from Anthropic:
```json
{
"message": {
"id": "msg_h87n43hife...",
"role": "assistant",
"model": "claude-3-5-sonnet-20241022",
"type": "message",
"stop_reason": "tool_use",
"stop_sequence": null,
"content": [
{
"type": "tool_use",
"id": "toolu_iudsn7es...",
"name": "respond",
"input": {
"table": [
{
"name": "John Smith",
"age": 30,
"email": "john.smith@email.com"
}
]
}
}
],
"usage": {
"input_tokens": 446,
"output_tokens": 72,
"cache_creation_input_tokens": 0, …
```
> bug(llmo): fix anthropic tool call response

- CHANGELOG.md
- posthog/ai/gemini/gemini.py
- posthog/test/ai/gemini/test_gemini.py
- posthog/version.py
Some users requested the ability to use Vertex AI authentication instead of requiring API keys for the Gemini client wrapper. This adds Vertex AI authentication support to the Gemini client.
```
client = Client(vertexai=True, location="location", project="my-project")
```
```
client = Client(api_key="your-key")
```
> feat(llmo): support Vertex AI

- example.py
- posthog/client.py
- posthog/feature_flags.py
- posthog/test/test_feature_flags.py
Add support for evaluating feature flag dependencies in local evaluation mode by [leveraging the new format deployed in this PR](https://github.com/PostHog/posthog/pull/36693).
Key features:
- Support for type="flag" properties with `dependency_chain` arrays
- Sequential evaluation following pre-computed dependency chain order
- Circular dependency detection (empty chain → InconclusiveMatchError)
- Missing flag dependency handling (evaluate as InconclusiveMatchError)
- Evaluation result caching for performance optimization
- Full backward compatibility with existing local evaluation
Once this is merged, I'll crank out a PR for all the other SDKs based on this implementation pattern.
> feat(flags): implement local evaluation of flag dependency filters

- CHANGELOG.md
- posthog/version.py
Forgot to bump version to 6.6.1 in my previous [PR](https://github.com/PostHog/posthog-python/pull/312)
> chore: bump version to 6.6.1

- bin/docs_scripts/doc_constant.py
- bin/docs_scripts/generate_json_schemas.py
- posthog/ai/anthropic/anthropic.py
- posthog/ai/openai/openai_async.py
- posthog/client.py
To unlock category filters in reference docs. This lets us link to references per product. The UI here isn't final.
https://github.com/user-attachments/assets/422b02f7-cf6a-40fb-b205-60b2010fb27e
Also fixes a small bug where we're showing empty types
> Add categories to doc specs

- CHANGELOG.md
- posthog/ai/anthropic/anthropic.py
- posthog/ai/anthropic/anthropic_async.py
- posthog/ai/gemini/gemini.py
- posthog/ai/langchain/callbacks.py
- posthog/ai/openai/openai.py
- posthog/ai/openai/openai_async.py
- posthog/ai/sanitization.py
- posthog/ai/utils.py
- posthog/test/ai/test_sanitization.py
- posthog/version.py
Removes base64 images from LLM traces to prevent them from exceeding the maximum event size. Replicates [the logic](https://github.com/PostHog/posthog-js/pull/2217) recently introduced into the JS SDK. Resolves #305.
> feat(llma): redact base64 images

- posthog/client.py
- posthog/test/test_feature_flags.py
> fix(flags): we don't fallback to `/decide` any more

- CHANGELOG.md
- posthog/ai/anthropic/anthropic.py
- posthog/ai/anthropic/anthropic_async.py
- posthog/ai/anthropic/anthropic_converter.py
- posthog/ai/gemini/gemini.py
- posthog/ai/gemini/gemini_converter.py
- posthog/ai/openai/openai.py
- posthog/ai/openai/openai_async.py
- posthog/ai/openai/openai_converter.py
- posthog/ai/types.py
- posthog/ai/utils.py
- posthog/test/ai/anthropic/test_anthropic.py
- posthog/test/ai/gemini/test_gemini.py
- posthog/version.py
Gemini wasn't sending reasoning and cached read tokens to the backend.
This:
- starts sending those tokens
- refactors the usage data extraction to live in the converter files and have proper typing
> fix(llma): gemini missing cached and reasoning tokens

- posthog/client.py
- posthog/test/test_client.py
- posthog/test/test_module.py
The goal is to ensure that our client doesn't cause a panic in an end-user application. This change updates
capture/set/set_once/group_identify/alias to swallow and log any exceptions that occur. Note that this won't prevent errors from propagating via the `on_error` callback if an error occurs while processing the queue.
Other methods like feature flags are documented to raise exceptions:
https://posthog.com/docs/libraries/python#error-handling
Resolves [#36982](https://github.com/PostHog/posthog/issues/36982)
> fix: Prevent core Client methods from raising exceptions
